disk_size: 50
image_base_name: de-vm-test-machine-image
instance_name: de-vm-test-machine
instance_user: lscr
machine_type: e2-standard-4
project_id: wagon-de
region: europe-central2
zone: europe-central2-b
